{% set name = "lalinspiral" %}
{% set version = "1.10.1" %}
{% set sha256 = "c6391d829e96d6cf5f21eb278d192f95a6ddd09150dd77fb659aadd0afe0a088" %}

{% set lal_version = "7.0.0" %}
{% set lalburst_version = "1.5.3" %}
{% set lalframe_version = "1.5.0" %}
{% set lalmetaio_version = "1.6.0" %}
{% set lalsimulation_version = "2.1.0" %}
{% set swig_version = "3.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  error_overdepending: true
  error_overlinking: true
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - pkg-config >=0.18.0
    - swig >={{ swig_version }}
  host:
    - gsl
    - lal >={{ lal_version }}
    - lalframe >={{ lalframe_version }}
    - lalmetaio >={{ lalmetaio_version }}
    - lalsimulation >={{ lalsimulation_version }}
    - metaio
  run:
    - gsl
    - lal >={{ lal_version }}
    - lalframe >={{ lalframe_version }}
    - lalmetaio >={{ lalmetaio_version }}
    - lalsimulation >={{ lalsimulation_version }}
    - metaio

test:
  requires:
    - pkg-config  # [unix]
  commands:
    - lalinspiral_version --verbose
    - test "$(pkg-config --modversion ${PKG_NAME})" == "${PKG_VERSION}"  # [unix]

outputs:
  - name: lalinspiral
    build:
      run_exports:
        - {{ pin_subpackage("lalinspiral", max_pin="x.x") }}

  - name: python-lalinspiral
    build:
      ignore_run_exports:
        # we don't actually use lalburst, but need it to ./configure
        # unfortunately, swig overlinks liblalburst into the python
        # bindings on linux
        - lalburst  # [not linux]
        # nothing actually links against libpython
        - python
    script: install-python.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - make
        - pkg-config >=0.18.0
        - swig >={{ swig_version }}
      host:
        - {{ pin_subpackage('lalinspiral', exact=True) }}
        - lalburst >={{ lalburst_version }}
        - numpy
        - python
      run:
        - gsl  # [linux]
        - lal >={{ lal_version }}
        - {{ pin_subpackage('lalinspiral', exact=True) }}
        - lalburst  # [linux]
        - lalframe  # [linux]
        - lalmetaio  # [linux]
        - lalsimulation  # [linux]
        - lscsoft-glue
        - metaio  # [linux]
        - {{ pin_compatible('numpy') }}
        - python
        - python-lal >={{ lal_version }}
        - python-lalburst >={{ lalburst_version }}
        - python-lalframe >={{ lalframe_version }}
        - python-lalmetaio >={{ lalmetaio_version }}
        - python-lalsimulation >={{ lalsimulation_version }}
        - python-ligo-lw
    test:
      imports:
        - lalinspiral
        - lalinspiral.inspinjfind
        - lalinspiral.sbank
        - lalinspiral.thinca
      requires:
        - pytest >=4.0.0a0
      source_files:
        - test/python
      commands:
        - pushd test/python; python -m pytest -v; popd
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://docs.ligo.org/lscsoft/lalsuite/lalinspiral/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Inspiral Library
      description: |
        The LSC Algorithm Inspiral Library for gravitational wave data analysis.
        This package contains the python bindings.

about:
  home: https://wiki.ligo.org/Computing/LALSuite
  doc_url: https://docs.ligo.org/lscsoft/lalsuite/lalinspiral/
  dev_url: https://git.ligo.org/lscsoft/lalsuite/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LSC Algorithm Inspiral Library
  description: |
    The LSC Algorithm Inspiral Library for gravitational wave data analysis.
    This package contains the shared-object libraries needed to run
    applications that use the LAL Inspiral library.  If you want to install
    the Python bindings, please install the associated python-lalinspiral
    package.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
