{% set name = "lalinspiral" %}
{% set version = "2.0.2" %}
{% set sha256 = "472fd96e2fe8645b0bc781376bece4fc54ccbb311975dc6a38477cbd3b3e2ca3" %}

# dependencies
{% set lal_version = "7.1.0" %}
{% set lalframe_version = "1.5.0" %}
{% set lalmetaio_version = "2.0.0" %}
{% set lalsimulation_version = "2.5.0" %}
{% set lalburst_version = "1.5.3" %}
{% set swig_version = "3.0.10" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  error_overdepending: true
  error_overlinking: true
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - help2man >=1.37
    - pkg-config >=0.18.0
    - swig >={{ swig_version }}
  host:
    - gsl
    - liblal >={{ lal_version }}
    - liblalframe >={{ lalframe_version }}
    - liblalmetaio >={{ lalmetaio_version }}
    - liblalsimulation >={{ lalsimulation_version }}
    - metaio

outputs:
  - name: liblalinspiral
    script: install-lib.sh
    build:
      error_overdepending: true
      error_overlinking: true
      run_exports:
        - {{ pin_subpackage("liblalinspiral", max_pin="x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - make
        - swig >={{ swig_version }}
      host:
        - gsl
        - liblal >={{ lal_version }}
        - liblalframe >={{ lalframe_version }}
        - liblalmetaio >={{ lalmetaio_version }}
        - liblalsimulation >={{ lalsimulation_version }}
        - metaio
      run:
        - gsl
        - liblal >={{ lal_version }}
        - liblalframe >={{ lalframe_version }}
        - liblalmetaio >={{ lalmetaio_version }}
        - liblalsimulation >={{ lalsimulation_version }}
        - metaio
      run_constrained:
        - lalinspiral >=2.0.1
        - python-lalinspiral >=2.0.1
    test:
      requires:
        - pkg-config
      commands:
        # check library
        - test -f ${PREFIX}/lib/liblalinspiral${SHLIB_EXT}  # [unix]
        # check activate variables
        - test "${LALINSPIRAL_DATADIR}" = "${PREFIX}/share/lalinspiral"  # [unix]
        # check pkg-config
        - pkg-config --print-errors --exact-version "${PKG_VERSION}" lalinspiral
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://docs.ligo.org/lscsoft/lalsuite/lalinspiral/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Inspiral Library shared object libraries
      description: |
        The LSC Algorithm Inspiral Library for gravitational wave data analysis.
        This package contains the shared object libraries needed to run
        applications that use the LAL Inspiral library.

  - name: python-lalinspiral
    script: install-python.sh
    build:
      error_overdepending: true
      error_overlinking: true
      ignore_run_exports:
        # we don't actually use lalburst, but need it to ./configure
        - liblalburst
        # nothing actually links against libpython
        - python
    requirements:
      build:
        - {{ compiler('c') }}
        - help2man >=1.37
        - make
        - pkg-config >=0.18.0
        - swig >={{ swig_version }}
      host:
        - {{ pin_subpackage('liblalinspiral', exact=True) }}
        - liblalburst >={{ lalburst_version }}
        - numpy
        - python
      run:
        - {{ pin_subpackage('liblalinspiral', exact=True) }}
        - lscsoft-glue
        - {{ pin_compatible('numpy') }}
        - python
        - python-lal >={{ lal_version }}
        - python-lalburst >={{ lalburst_version }}
        - python-lalframe >={{ lalframe_version }}
        - python-lalmetaio >={{ lalmetaio_version }}
        - python-lalsimulation >={{ lalsimulation_version }}
        - python-ligo-lw
    test:
      requires:
        - pytest >=4.0.0a0
      source_files:
        - test/python
      commands:
        - python -m pytest -ra -v test/python
      imports:
        - lalinspiral
        - lalinspiral.inspinjfind
        - lalinspiral.sbank
        - lalinspiral.thinca
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://docs.ligo.org/lscsoft/lalsuite/lalinspiral/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Inspiral Library Python libraries
      description: |
        The LSC Algorithm Inspiral Library for gravitational wave data analysis.
        This package contains the Python bindings of the LALInspiral C libraries
        and additional Python modules.

        Note: this package only provides the importable Python libraries.
        All command-line interfaces, scripts, and executables are
        part of the `lalinspiral` package.

  - name: lalinspiral
    script: install-bin.sh
    build:
      error_overdepending: true
      error_overlinking: true
      ignore_run_exports:
        - liblalburst
        - python
    requirements:
      build:
        - {{ compiler('c') }}
        - help2man >=1.37
        - make
      host:
        - liblal >={{ lal_version }}
        - liblalburst >={{ lalburst_version }}
        - {{ pin_subpackage('liblalinspiral', exact=True) }}
        - python
      run:
        - liblal >={{ lal_version }}
        - {{ pin_subpackage('liblalinspiral', exact=True) }}
        - python
        - {{ pin_subpackage('python-lalinspiral', exact=True) }}
    test:
      commands:
        - lalinspiral_version --verbose
      imports:
        - lalinspiral
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://docs.ligo.org/lscsoft/lalsuite/lalinspiral/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Inspiral Library
      description: |
        The LSC Algorithm Inspiral Library for gravitational wave data analysis.

about:
  home: https://wiki.ligo.org/Computing/LALSuite
  doc_url: https://docs.ligo.org/lscsoft/lalsuite/lalinspiral/
  dev_url: https://git.ligo.org/lscsoft/lalsuite/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LSC Algorithm Inspiral Library
  description: |
    The LSC Algorithm Inspiral Library for gravitational wave data analysis.

extra:
  feedstock-name: lalinspiral
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
